### ISSUE TITLE
Support for SASL authentication with encrypted password

### ISSUE THREAD

**Issue by apiraino** [async-email/async-imap#38]
Hello,

I was using DeltaChat a while ago (which uses your crate) and I [could not have their client authenthicate](https://github.com/deltachat/deltachat-core-rust/issues/1427) with SASL, encrypted connection and password.

My understanding is that this is not yet supported by async-imap - is this something you would evaluate for implementation at some point? I'm speaking as the final user with very vague idea of the effort needed, so I'll be happy to receive some more context.

Thanks for working on this crate by the way :)

**Comment by hpk42** [comment]
we just had a discussion on our #deltachat irc channel -- it seems that SASL with encrypted passwords only makes sense if you don't have TLS.  In fact, TLS not only protects the password, but also retrieving mails, so it's much preferable these days.  At the time SASL was created (around 2003) TLS was not widespread but nowadays most servers support it.  Note that SASL/protected passwords also require the server to store the password in clear form (not hashed, as is typical nowadays) so someone hacking into such a server will get all passwords of the users. That's probably the reason why hardly any email server supports it these days. Therefore closing this issue with wont-fix.  Thanks for bringing it up, though. It helped to clarify this longer standing question/issue.

**Comment by apiraino** [comment]
Thank you so much for the explaination! Definitively an interesting read and a learning experience.

**Comment by hpk42** [comment]
you are welcome!

**Comment by wilhelmy** [comment]
I think it would still be nice to have in TLS encrypted connections. I'm by no means a cryptologist but the TLS is only as good as your certification authority and man-in-the-middle attacks do exist although they're rare. So the ability of never sending passwords in plain text if at all possible would be nice to have.

I think with SASL schemes of the SCRAM variety (e.g. SCRAM-SHA-256) the server doesn't need to store the password in plain text either.

I really don't see why you'd call SASL outdated, since it mostly just specifies a plugin system for various password authentication backends, and is fairly agnostic towards the individual authentication mechanisms.
